name: energy.communities
services:
  database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=disysuser
      - POSTGRES_PASSWORD=disyspw

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

  energy.server:
    image: energy.server:${APP_VERSION}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=disysuser
      - SPRING_DATASOURCE_PASSWORD=disyspw
    ports:
      - '8080:8080'

  energy.producer:
    image: energy.producer:${APP_VERSION}
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - '8081:8080'

  energy.user:
    image: energy.user:${APP_VERSION}
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - '8082:8080'

  current.percentage.service:
    image: current.percentage.service:${APP_VERSION}
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=disysuser
      - SPRING_DATASOURCE_PASSWORD=disyspw
    ports:
      - '8083:8080'

  usage.service:
    image: usage.service:${APP_VERSION}
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=disysuser
      - SPRING_DATASOURCE_PASSWORD=disyspw
    ports:
      - '8084:8080'