# interval random time range in ms - used to simulate production
producer.interval.from:1000
producer.interval.to:5000
# kwh range
kwh.range.from:0.001
kwh.range.to:1
#vienna = 48.210033, 16.363449
city.latitude=48.210033
city.longitude=16.363449